### PR TITLE
Fix Safari issue where it adds a .ps extension to downloaded files wi…

### PR DESCRIPTION
**Pull request by jnoer**
…th response-content-type application/postscript.

IT-1477

### CODE REVIEW

**Comment by aswenson** [comment]
I think this would still need to be refactored to add the content type as a configurable option but agree with the AI part not being explicitly included:
```new CloudfrontUrlBuilder("host")
	  .withAttachmentFilename("foo.ai")
	  .withContentType("application/octet-stream");```

**Comment by jnoer** [comment]
Makes sense. I moved this into amazon-widen, but it's still in a library. Do you think I should create a new method in CloudFrontUrlServiceImpl for DAM to call?

**Comment by jnoer** [comment]
https://github.com/Widen/amazon-widen/commit/6eaf8421ad9186e6045fb0f76110a9cc3129128a

**Comment by jnoer** [comment]
Ok, @aswenson. See also these PRs.

https://github.com/Widen/amazon-widen/pull/18/files
https://github.com/Widen/dam/pull/1123

**Pull request merged**
